// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const getSystemMeta = `-- name: GetSystemMeta :one
SELECT key, val, created_at
FROM _system_meta
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSystemMeta(ctx context.Context, key string) (SystemMetum, error) {
	row := q.db.QueryRow(ctx, getSystemMeta, key)
	var i SystemMetum
	err := row.Scan(&i.Key, &i.Val, &i.CreatedAt)
	return i, err
}
