// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchJobs = `-- name: CountSearchJobs :one
SELECT COUNT(*)
FROM jobs
WHERE
    ($1::text IS NULL OR (
        title ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
        OR company ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
        OR description ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
    ))
    AND ($2::text IS NULL OR city ILIKE '%' || $2::text || '%')
    AND ($3::text IS NULL OR state ILIKE $3::text)
    AND ($4::text IS NULL OR company ILIKE '%' || $4::text || '%')
    AND ($5::text IS NULL OR source = $5::text)
    AND ($6::text IS NULL OR status = $6::text)
    AND ($7::timestamptz IS NULL OR published_at >= $7::timestamptz)
    AND ($8::timestamptz IS NULL OR published_at <= $8::timestamptz)
`

type CountSearchJobsParams struct {
	Query          pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	Company        pgtype.Text
	Source         pgtype.Text
	Status         pgtype.Text
	PublishedSince pgtype.Timestamptz
	PublishedUntil pgtype.Timestamptz
}

func (q *Queries) CountSearchJobs(ctx context.Context, arg CountSearchJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchJobs,
		arg.Query,
		arg.City,
		arg.State,
		arg.Company,
		arg.Source,
		arg.Status,
		arg.PublishedSince,
		arg.PublishedUntil,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status
) VALUES (
    COALESCE(NULLIF($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid), uuidv7()),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
`

type CreateJobParams struct {
	ID             uuid.UUID
	ExternalID     string
	Title          string
	Company        string
	Description    string
	City           string
	State          string
	Source         string
	SourceUrl      string
	Fingerprint    string
	WorkMode       string
	EmploymentType string
	SalaryMin      pgtype.Int8
	SalaryMax      pgtype.Int8
	PublishedAt    pgtype.Timestamptz
	CollectedAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Status         string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.ExternalID,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.City,
		arg.State,
		arg.Source,
		arg.SourceUrl,
		arg.Fingerprint,
		arg.WorkMode,
		arg.EmploymentType,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.PublishedAt,
		arg.CollectedAt,
		arg.LastSeenAt,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.City,
		&i.State,
		&i.Source,
		&i.SourceUrl,
		&i.Fingerprint,
		&i.WorkMode,
		&i.EmploymentType,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PublishedAt,
		&i.CollectedAt,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobsByIDs = `-- name: DeleteJobsByIDs :execrows
DELETE FROM jobs
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteJobsByIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJobsByIDs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobByFingerprint = `-- name: GetJobByFingerprint :one
SELECT
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
FROM jobs
WHERE fingerprint = $1
LIMIT 1
`

func (q *Queries) GetJobByFingerprint(ctx context.Context, fingerprint string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByFingerprint, fingerprint)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.City,
		&i.State,
		&i.Source,
		&i.SourceUrl,
		&i.Fingerprint,
		&i.WorkMode,
		&i.EmploymentType,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PublishedAt,
		&i.CollectedAt,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.City,
		&i.State,
		&i.Source,
		&i.SourceUrl,
		&i.Fingerprint,
		&i.WorkMode,
		&i.EmploymentType,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PublishedAt,
		&i.CollectedAt,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobBySourceAndExternalID = `-- name: GetJobBySourceAndExternalID :one
SELECT
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
FROM jobs
WHERE source = $1 AND external_id = $2
`

type GetJobBySourceAndExternalIDParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) GetJobBySourceAndExternalID(ctx context.Context, arg GetJobBySourceAndExternalIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobBySourceAndExternalID, arg.Source, arg.ExternalID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.City,
		&i.State,
		&i.Source,
		&i.SourceUrl,
		&i.Fingerprint,
		&i.WorkMode,
		&i.EmploymentType,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PublishedAt,
		&i.CollectedAt,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveJobsForPruning = `-- name: ListActiveJobsForPruning :many
SELECT id, title, description, city, state, company, source
FROM jobs
WHERE status = 'ACTIVE'
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListActiveJobsForPruningParams struct {
	Limit  int32
	Offset int32
}

type ListActiveJobsForPruningRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	City        string
	State       string
	Company     string
	Source      string
}

func (q *Queries) ListActiveJobsForPruning(ctx context.Context, arg ListActiveJobsForPruningParams) ([]ListActiveJobsForPruningRow, error) {
	rows, err := q.db.Query(ctx, listActiveJobsForPruning, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveJobsForPruningRow
	for rows.Next() {
		var i ListActiveJobsForPruningRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.City,
			&i.State,
			&i.Company,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many
SELECT
    city,
    state,
    COUNT(*)::bigint AS total_jobs
FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND city != ''
GROUP BY city, state
ORDER BY city ASC, state ASC
`

type ListCitiesRow struct {
	City      string
	State     string
	TotalJobs int64
}

func (q *Queries) ListCities(ctx context.Context, status pgtype.Text) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesRow
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(&i.City, &i.State, &i.TotalJobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT
    company AS name,
    COUNT(*)::bigint AS total_jobs
FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND company != ''
GROUP BY company
ORDER BY company ASC
`

type ListCompaniesRow struct {
	Name      string
	TotalJobs int64
}

func (q *Queries) ListCompanies(ctx context.Context, status pgtype.Text) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesRow
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(&i.Name, &i.TotalJobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
FROM jobs
ORDER BY published_at DESC NULLS LAST, id DESC
LIMIT $2 OFFSET $1
`

type ListJobsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.Company,
			&i.Description,
			&i.City,
			&i.State,
			&i.Source,
			&i.SourceUrl,
			&i.Fingerprint,
			&i.WorkMode,
			&i.EmploymentType,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.PublishedAt,
			&i.CollectedAt,
			&i.LastSeenAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT
    source,
    COUNT(*)::bigint AS total_jobs
FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND source != ''
GROUP BY source
ORDER BY source ASC
`

type ListSourcesRow struct {
	Source    string
	TotalJobs int64
}

func (q *Queries) ListSources(ctx context.Context, status pgtype.Text) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourcesRow
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(&i.Source, &i.TotalJobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobsExpired = `-- name: MarkJobsExpired :execrows
UPDATE jobs
SET status = 'EXPIRED', updated_at = NOW()
WHERE status = 'UNKNOWN' AND last_seen_at < $1
`

func (q *Queries) MarkJobsExpired(ctx context.Context, beforeTime pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markJobsExpired, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobsUnknown = `-- name: MarkJobsUnknown :execrows
UPDATE jobs
SET status = 'UNKNOWN', updated_at = NOW()
WHERE status = 'ACTIVE' AND last_seen_at < $1
`

func (q *Queries) MarkJobsUnknown(ctx context.Context, beforeTime pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markJobsUnknown, beforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
FROM jobs
WHERE
    ($1::text IS NULL OR (
        title ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
        OR company ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
        OR description ILIKE ANY (SELECT '%' || trim(t) || '%' FROM unnest(string_to_array($1::text, ',')) AS t WHERE trim(t) != '')
    ))
    AND ($2::text IS NULL OR city ILIKE '%' || $2::text || '%')
    AND ($3::text IS NULL OR state ILIKE $3::text)
    AND ($4::text IS NULL OR company ILIKE '%' || $4::text || '%')
    AND ($5::text IS NULL OR source = $5::text)
    AND ($6::text IS NULL OR status = $6::text)
    AND ($7::timestamptz IS NULL OR published_at >= $7::timestamptz)
    AND ($8::timestamptz IS NULL OR published_at <= $8::timestamptz)
ORDER BY published_at DESC NULLS LAST, id DESC
LIMIT $10 OFFSET $9
`

type SearchJobsParams struct {
	Query          pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	Company        pgtype.Text
	Source         pgtype.Text
	Status         pgtype.Text
	PublishedSince pgtype.Timestamptz
	PublishedUntil pgtype.Timestamptz
	OffsetCount    int32
	LimitCount     int32
}

func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, searchJobs,
		arg.Query,
		arg.City,
		arg.State,
		arg.Company,
		arg.Source,
		arg.Status,
		arg.PublishedSince,
		arg.PublishedUntil,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.Company,
			&i.Description,
			&i.City,
			&i.State,
			&i.Source,
			&i.SourceUrl,
			&i.Fingerprint,
			&i.WorkMode,
			&i.EmploymentType,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.PublishedAt,
			&i.CollectedAt,
			&i.LastSeenAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET
    title = $1,
    company = $2,
    description = $3,
    city = $4,
    state = $5,
    source_url = $6,
    fingerprint = $7,
    work_mode = $8,
    employment_type = $9,
    salary_min = $10,
    salary_max = $11,
    published_at = $12,
    status = $13,
    updated_at = NOW()
WHERE id = $14
RETURNING
    id,
    external_id,
    title,
    company,
    description,
    city,
    state,
    source,
    source_url,
    fingerprint,
    work_mode,
    employment_type,
    salary_min,
    salary_max,
    published_at,
    collected_at,
    last_seen_at,
    status,
    created_at,
    updated_at
`

type UpdateJobParams struct {
	Title          string
	Company        string
	Description    string
	City           string
	State          string
	SourceUrl      string
	Fingerprint    string
	WorkMode       string
	EmploymentType string
	SalaryMin      pgtype.Int8
	SalaryMax      pgtype.Int8
	PublishedAt    pgtype.Timestamptz
	Status         string
	ID             uuid.UUID
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.City,
		arg.State,
		arg.SourceUrl,
		arg.Fingerprint,
		arg.WorkMode,
		arg.EmploymentType,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.PublishedAt,
		arg.Status,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.City,
		&i.State,
		&i.Source,
		&i.SourceUrl,
		&i.Fingerprint,
		&i.WorkMode,
		&i.EmploymentType,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PublishedAt,
		&i.CollectedAt,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobLastSeen = `-- name: UpdateJobLastSeen :one
UPDATE jobs
SET
    last_seen_at = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, last_seen_at, updated_at
`

type UpdateJobLastSeenParams struct {
	LastSeenAt pgtype.Timestamptz
	ID         uuid.UUID
}

type UpdateJobLastSeenRow struct {
	ID         uuid.UUID
	LastSeenAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateJobLastSeen(ctx context.Context, arg UpdateJobLastSeenParams) (UpdateJobLastSeenRow, error) {
	row := q.db.QueryRow(ctx, updateJobLastSeen, arg.LastSeenAt, arg.ID)
	var i UpdateJobLastSeenRow
	err := row.Scan(&i.ID, &i.LastSeenAt, &i.UpdatedAt)
	return i, err
}
